# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
puts "Seeding Data..."

TravelMethod.create(name: "Plane")
TravelMethod.create(name: "Train")
TravelMethod.create(name: "Automobile")

MethodTask.create(name: "Print boarding pass.", description: "Make sure you have selected your seat as well, if applicable.", complete: false, due_date: 1, travel_method_id: 1)
MethodTask.create(name: "Print boarding pass.", description: "Make sure you have selected your seat as well, if applicable.", complete: false, due_date: 1, travel_method_id: 2)
MethodTask.create(name: "Determine travel time to station.", description: "Figure out how long it will take you get to the station and how early you need to be there.", complete: false, due_date: 3, travel_method_id: 2)
MethodTask.create(name: "Determine travel time to airport.", description: "Figure out how long it will take you get to the airport and how early you need to be there.", complete: false, due_date: 3, travel_method_id: 1)
MethodTask.create(name: "Determine how you'll get to station.", description: "Choose how you're getting to the station.", complete: false, due_date: 3, travel_method_id: 2)
MethodTask.create(name: "Determine how you'll get to airport.", description: "Choose how you're getting to the airport.", complete: false, due_date: 3, travel_method_id: 1)
MethodTask.create(name: "Get gas.", description: "You won't want to stop for gas shortly after leaving, so fill up before you start.", complete: false, due_date: 1, travel_method_id: 3)
MethodTask.create(name: "Decide if accommodations are needed.", description: "If you're driving longer than 8 hours, you may want to stay overnight somewhere. Do some research and find a nice place to stay.", complete: false, due_date: 21, travel_method_id: 3)
MethodTask.create(name: "Get something to listen to.", description: "Make yourself a playlist, or ask people for podcast or audiobook recommendations.", complete: false, due_date: 7, travel_method_id: 1)
MethodTask.create(name: "Get something to listen to.", description: "Make yourself a playlist, or ask people for podcast or audiobook recommendations.", complete: false, due_date: 7, travel_method_id: 2)
MethodTask.create(name: "Get something to listen to.", description: "Make yourself a playlist, or ask people for podcast or audiobook recommendations.", complete: false, due_date: 7, travel_method_id: 3)
MethodTask.create(name: "Get packing.", description: "Check the weather for your trip and also consider if you'll be going to any events. If you start early, you'll have time to shop for things you need.", complete: false, due_date: 4, travel_method_id: 1)
MethodTask.create(name: "Get packing.", description: "Check the weather for your trip and also consider if you'll be going to any events. If you start early, you'll have time to shop for things you need.", complete: false, due_date: 4, travel_method_id: 2)
MethodTask.create(name: "Get packing.", description: "Check the weather for your trip and also consider if you'll be going to any events. If you start early, you'll have time to shop for things you need.", complete: false, due_date: 4, travel_method_id: 3)
MethodTask.create(name: "Bring snacks.", description: "Who doesn't like snacking? Make sure you also bring water to stay hydrated.", complete: false, due_date: 1, travel_method_id: 2)
MethodTask.create(name: "Bring snacks.", description: "Who doesn't like snacking? Make sure you also bring water to stay hydrated.", complete: false, due_date: 1, travel_method_id: 3)
MethodTask.create(name: "Bring snacks.", description: "Who doesn't like snacking?", complete: false, due_date: 1, travel_method_id: 1)
MethodTask.create(name: "Bring offline activity.", description: "If there won't be WiFi, you still want to remain occupied. Grab the book you've been meaning to read or a book of crossword puzzles.", complete: false, due_date: 1, travel_method_id: 1)
MethodTask.create(name: "Bring offline activity.", description: "If there won't be WiFi, you still want to remain occupied. Grab the book you've been meaning to read or a book of crossword puzzles.", complete: false, due_date: 1, travel_method_id: 2)
MethodTask.create(name: "Charge your devices.", description: "There's not always an outlet available, so make sure you're juiced up!", complete: false, due_date: 1, travel_method_id: 1)
MethodTask.create(name: "Charge your devices.", description: "There's not always an outlet available, so make sure you're juiced up!", complete: false, due_date: 1, travel_method_id: 2)
MethodTask.create(name: "Charge your devices.", description: "There's not always an outlet available, so make sure you're juiced up!", complete: false, due_date: 1, travel_method_id: 3)
MethodTask.create(name: "Bring your chargers.", description: "You may have charged your devices, but that battery won't last the whole trip.", complete: false, due_date: 1, travel_method_id: 1)
MethodTask.create(name: "Bring your chargers.", description: "You may have charged your devices, but that battery won't last the whole trip.", complete: false, due_date: 1, travel_method_id: 2)
MethodTask.create(name: "Bring your chargers.", description: "You may have charged your devices, but that battery won't last the whole trip.", complete: false, due_date: 1, travel_method_id: 3)
MethodTask.create(name: "Confirm PTO.", description: "Make sure you can actually go on this trip.", complete: false, due_date: 28, travel_method_id: 1)
MethodTask.create(name: "Confirm PTO.", description: "Make sure you can actually go on this trip.", complete: false, due_date: 28, travel_method_id: 2)
MethodTask.create(name: "Confirm PTO.", description: "Make sure you can actually go on this trip.", complete: false, due_date: 28, travel_method_id: 3)
MethodTask.create(name: "Set OOO message.", description: "Nothing worse than having to work on vacation. That's a work trip.", complete: false, due_date: 1, travel_method_id: 1)
MethodTask.create(name: "Set OOO message.", description: "Nothing worse than having to work on vacation. That's a work trip.", complete: false, due_date: 1, travel_method_id: 2)
MethodTask.create(name: "Set OOO message.", description: "Nothing worse than having to work on vacation. That's a work trip.", complete: false, due_date: 1, travel_method_id: 3)
MethodTask.create(name: "Confirm COVID requirements of destination", description: "Some places require a PCR and those can take a few days to process. Plan accordingly.", complete: false, due_date: 7, travel_method_id: 1)
MethodTask.create(name: "Confirm COVID requirements of destination", description: "Some places require a PCR and those can take a few days to process. Plan accordingly.", complete: false, due_date: 7, travel_method_id: 2)
MethodTask.create(name: "Confirm COVID requirements of destination", description: "Some places require a PCR and those can take a few days to process. Plan accordingly.", complete: false, due_date: 7, travel_method_id: 3)
MethodTask.create(name: "Throw out your perishables.", description: "Not as bad as working on vacation, but coming home to rotten food is not fun.", complete: false, due_date: 1, travel_method_id: 1)
MethodTask.create(name: "Throw out your perishables.", description: "Not as bad as working on vacation, but coming home to rotten food is not fun.", complete: false, due_date: 1, travel_method_id: 2)
MethodTask.create(name: "Throw out your perishables.", description: "Not as bad as working on vacation, but coming home to rotten food is not fun.", complete: false, due_date: 1, travel_method_id: 3)
MethodTask.create(name: "Have essentials in your carry-on luggage.", description: "You want to have a toothbrush and fresh underwear if your checked luggage is lost.", complete: false, due_date: 1, travel_method_id: 1)
MethodTask.create(name: "Have car checked out for any issues.", description: "Take care of those 'change oil' and 'fill wiper fluid' notifications before you leave for the trip.", complete: false, due_date: 7, travel_method_id: 3)
MethodTask.create(name: "Get parking passes.", description: "Check to see if you need anything to drive where you're going. National parks frequently require passes than can be cheaper if bought in advance.", complete: false, due_date: 14, travel_method_id: 3)
MethodTask.create(name: "Hire a pet-sitter.", description: "Someone's gotta take care of the fur babies.", complete: false, due_date: 21, travel_method_id: 1)
MethodTask.create(name: "Hire a pet-sitter.", description: "Someone's gotta take care of the fur babies.", complete: false, due_date: 21, travel_method_id: 2)
MethodTask.create(name: "Hire a pet-sitter.", description: "Someone's gotta take care of the fur babies.", complete: false, due_date: 21, travel_method_id: 3)
MethodTask.create(name: "Book tickets!", description: "It's not fun for your bank account, but it makes the trip real!", complete: false, due_date: 27, travel_method_id: 1)
MethodTask.create(name: "Book tickets!", description: "It's not fun for your bank account, but it makes the trip real!", complete: false, due_date: 27, travel_method_id: 1)

puts "Seeded!"